travis:
  secure:
    BINSTAR_TOKEN: htDQqat2pmeMmEIYW5KZ6JREYroJeTxiV0Jvdy6QlG2cG+acvy2yA2N+TzCez/x2BVdBjtqfDVSCedFpTueA2Z/v8YLHj+go4SN6YtgBEGwrnliPi5q8ugFJVws3M6TR6HBWn7HUZx0nz20kpCNLbiJVtxNmZpSawcsiyLToZlxgZI2NM/FqFvy6SGx/JM2vG4l8ypO0j/zXDL28nURdqubKDa8lJA3SqEAMgqdwT/h+9zm1zqSBqUXJEzHoTuO+YzcPxSgGQ1hykb3Ws5QZf/jmboAj4Cv1eqhtPz3zJ30mfzP3xZgstJ4DNlHelY16V+q4kJ6VP0OGzzRhrr0ChLk8gySgdklmqbKx7L+IT6ZomiiLGSCRm7jshlZSpmfNThr9wnMqmtS9jQSYaoS+wWS94ALvbiZJv1qjxx44xa9xjsfX+UPkGJhIvkwqgfxJYjdKRFv3N4ApnrG0dCCoT7pzhLUJBtcjqhFTekfZ4BoClu4d9mWPGPvDZ63CoGctRvPdYdbqmP+YD55NahTMIdJleQS9L+xkS5O0VXzvsdwvihAuN8IuX13tVKVt2ZzBHO32CkeiY+iRaRpk3oI/J6Rzo0oKswggbPnf3glKekpNa3VkqxzQJc+MZfNirvs7i61nLKvSWz5fkppNO9aDxwKpTczHlvbuySUpQAEtzPA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
