travis:
  secure:
    BINSTAR_TOKEN: viA+cjIKJtlmqFEODROnTtYefA6xIF+N2pJci5X9yP+odKgqE11Yvfw4Fv3uRoP2pw80IS/CPe4QfnmUI/CPNrnzbPn00bUfOZqgwmmcszC90ZcFBAgm0bq71Go5I//h+XMqs53hPOh4bvUmqUDRT/PzWaRpS8UvwY4PuO9ESVmONiQhBpKYenYlWVeZhxD2VYdn0v6uMw+DFzRToG/EHwscMcQgFyCR320xSoC9ncUeYP86uZuZPQF/bLnT9xLq+Y5qRdlBQT0IicGDqv4v16OXBhz7ZuCGhTPoU3ynVRhgReNiB7J9F3mvQKoozgGJYR6eEzKDDqY8fIniS4hYzTtg2za2LOz4d9BvlUB2D0AKQBkOlBwdPcFm/wGIEiMih+e2/EimiTtLK3F7ydAyc/RQdz7QmfBOzAs+X6CV2sunuhG0LVDIEd0lfCkK6ujloTowe13j1Q117qBaL9ZuqAhoHhkkBJSRbrf8pcSJdppo0X81flQ5G8h1RdS400R+rVXh6qi14tRpLsRsr0P4uyEsIG3TgH05MWWG+ebcgFCPWC5lhm7cWQEsYiWoYY73jrAtIODAFL+6MCo+qVvx+ruaXi1DS8NG5LtWUoMluyHCILVwUvxXoAE+cmzb7zYilvQ9tZ5QBhvSOX/hCI/+da8d65atYRcFSh3S2svcN0c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
